layout: sidebar
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 9
  exclude:
    forks: true
    projects:
    # - repo-name

# social_media:
  # behance: your_username
  # dribbble: your_username
  # facebook: your_username
  # linkedin: your_username
  # medium: @your_username
  # stackoverflow: your_user_id
  # telegram: your_username
  # twitter: your_username
  # youtube: your_username
  # vk: your_username

topics:
  - name: Rust
    web_url: https://github.com/topics/rust
    image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/rust/rust.png

  - name: TypeScript
    web_url: https://github.com/topics/typescript
    image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/typescript/typescript.png

  - name: GraphQL
    web_url: https://github.com/topics/graphql
    image_url: https://raw.githubusercontent.com/github/explore/5c058a388828bb5fde0bcafd4bc867b5bb3f26f3/topics/graphql/graphql.png
